"use client";

import type { ComponentType, SVGProps } from "react";
import {
  AcademicCapIcon,
  ArrowPathIcon,
  BanknotesIcon,
  BellAlertIcon,
  BoltIcon,
  BriefcaseIcon,
  BuildingOffice2Icon,
  BuildingStorefrontIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  ChatBubbleLeftRightIcon,
  CheckBadgeIcon,
  ClipboardDocumentCheckIcon,
  ClockIcon,
  Cog6ToothIcon,
  CreditCardIcon,
  DevicePhoneMobileIcon,
  EnvelopeIcon,
  FireIcon,
  GiftIcon,
  GlobeAltIcon,
  HandThumbUpIcon,
  HeartIcon,
  HomeModernIcon,
  LifebuoyIcon,
  LightBulbIcon,
  LockClosedIcon,
  MapPinIcon,
  PhoneIcon,
  RocketLaunchIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  SparklesIcon,
  StarIcon,
  TagIcon,
  TicketIcon,
  TrophyIcon,
  TruckIcon,
  UserGroupIcon,
  WrenchIcon,
  WrenchScrewdriverIcon,
} from "@heroicons/react/24/outline";

export type TemplateIconCategory =
  | "service"
  | "trust"
  | "support"
  | "business"
  | "offers"
  | "people"
  | "locations"
  | "ideas";

export interface TemplateIconDefinition {
  id: string;
  label: string;
  category: TemplateIconCategory;
  keywords: string[];
  component: ComponentType<SVGProps<SVGSVGElement>>;
}

export const TEMPLATE_ICON_CATEGORY_LABELS: Record<TemplateIconCategory, string> = {
  service: "Service",
  trust: "Trust",
  support: "Support",
  business: "Business",
  offers: "Offers",
  people: "People",
  locations: "Locations",
  ideas: "Ideas",
};

export const TEMPLATE_ICON_LIBRARY: TemplateIconDefinition[] = [
  {
    id: "wrench-screwdriver",
    label: "Wrench & Screwdriver",
    category: "service",
    keywords: ["repair", "maintenance", "service", "technician", "garage"],
    component: WrenchScrewdriverIcon,
  },
  {
    id: "wrench",
    label: "Wrench",
    category: "service",
    keywords: ["repair", "maintenance", "tool", "service"],
    component: WrenchIcon,
  },
  {
    id: "clipboard-check",
    label: "Inspection",
    category: "service",
    keywords: ["inspection", "checklist", "quality", "review", "service"],
    component: ClipboardDocumentCheckIcon,
  },
  {
    id: "calendar-days",
    label: "Scheduling",
    category: "service",
    keywords: ["schedule", "appointment", "booking", "date"],
    component: CalendarDaysIcon,
  },
  {
    id: "clock",
    label: "Time Savings",
    category: "service",
    keywords: ["time", "fast", "quick", "hours"],
    component: ClockIcon,
  },
  {
    id: "arrow-path",
    label: "Repeat Service",
    category: "service",
    keywords: ["repeat", "refresh", "renew", "cycle"],
    component: ArrowPathIcon,
  },
  {
    id: "truck",
    label: "Pickup & Delivery",
    category: "service",
    keywords: ["delivery", "transport", "pickup", "mobile"],
    component: TruckIcon,
  },
  {
    id: "cog-6-tooth",
    label: "Precision",
    category: "service",
    keywords: ["settings", "precision", "engine", "system"],
    component: Cog6ToothIcon,
  },
  {
    id: "shield-check",
    label: "Trusted Protection",
    category: "trust",
    keywords: ["trust", "protection", "guarantee", "safe", "secure"],
    component: ShieldCheckIcon,
  },
  {
    id: "check-badge",
    label: "Certified",
    category: "trust",
    keywords: ["certified", "approved", "verified", "expert"],
    component: CheckBadgeIcon,
  },
  {
    id: "lock-closed",
    label: "Secure",
    category: "trust",
    keywords: ["secure", "safety", "private", "locked"],
    component: LockClosedIcon,
  },
  {
    id: "star",
    label: "Top Rated",
    category: "trust",
    keywords: ["rating", "favorite", "review", "premium"],
    component: StarIcon,
  },
  {
    id: "hand-thumb-up",
    label: "Recommended",
    category: "trust",
    keywords: ["recommended", "approved", "liked", "trusted"],
    component: HandThumbUpIcon,
  },
  {
    id: "trophy",
    label: "Award Winning",
    category: "trust",
    keywords: ["award", "winner", "best", "top"],
    component: TrophyIcon,
  },
  {
    id: "heart",
    label: "Care",
    category: "trust",
    keywords: ["care", "love", "community", "customer"],
    component: HeartIcon,
  },
  {
    id: "chat-bubble-left-right",
    label: "Consultation",
    category: "support",
    keywords: ["chat", "conversation", "message", "support", "questions"],
    component: ChatBubbleLeftRightIcon,
  },
  {
    id: "phone",
    label: "Call Support",
    category: "support",
    keywords: ["phone", "call", "contact", "support"],
    component: PhoneIcon,
  },
  {
    id: "envelope",
    label: "Email Support",
    category: "support",
    keywords: ["email", "contact", "message", "newsletter"],
    component: EnvelopeIcon,
  },
  {
    id: "bell-alert",
    label: "Alerts",
    category: "support",
    keywords: ["alert", "reminder", "notification", "bell"],
    component: BellAlertIcon,
  },
  {
    id: "lifebuoy",
    label: "Help Center",
    category: "support",
    keywords: ["help", "support", "assistance", "care"],
    component: LifebuoyIcon,
  },
  {
    id: "device-phone-mobile",
    label: "Mobile Updates",
    category: "support",
    keywords: ["mobile", "phone", "text", "sms", "app"],
    component: DevicePhoneMobileIcon,
  },
  {
    id: "building-storefront",
    label: "Storefront",
    category: "business",
    keywords: ["store", "dealer", "showroom", "location"],
    component: BuildingStorefrontIcon,
  },
  {
    id: "building-office-2",
    label: "Business",
    category: "business",
    keywords: ["office", "company", "team", "business"],
    component: BuildingOffice2Icon,
  },
  {
    id: "briefcase",
    label: "Professional",
    category: "business",
    keywords: ["professional", "business", "team", "work"],
    component: BriefcaseIcon,
  },
  {
    id: "chart-bar",
    label: "Performance",
    category: "business",
    keywords: ["analytics", "growth", "performance", "results"],
    component: ChartBarIcon,
  },
  {
    id: "banknotes",
    label: "Value",
    category: "business",
    keywords: ["value", "money", "savings", "price"],
    component: BanknotesIcon,
  },
  {
    id: "credit-card",
    label: "Flexible Payment",
    category: "business",
    keywords: ["payment", "finance", "billing", "card"],
    component: CreditCardIcon,
  },
  {
    id: "globe-alt",
    label: "Online Access",
    category: "business",
    keywords: ["web", "online", "global", "digital"],
    component: GlobeAltIcon,
  },
  {
    id: "home-modern",
    label: "Local Experience",
    category: "business",
    keywords: ["local", "community", "home", "nearby"],
    component: HomeModernIcon,
  },
  {
    id: "gift",
    label: "Gift",
    category: "offers",
    keywords: ["gift", "bonus", "special", "offer"],
    component: GiftIcon,
  },
  {
    id: "tag",
    label: "Special Offer",
    category: "offers",
    keywords: ["tag", "discount", "deal", "offer", "sale"],
    component: TagIcon,
  },
  {
    id: "ticket",
    label: "Coupon",
    category: "offers",
    keywords: ["coupon", "ticket", "voucher", "promo"],
    component: TicketIcon,
  },
  {
    id: "shopping-bag",
    label: "Package",
    category: "offers",
    keywords: ["bundle", "package", "offer", "shopping"],
    component: ShoppingBagIcon,
  },
  {
    id: "sparkles",
    label: "Premium",
    category: "offers",
    keywords: ["premium", "featured", "highlight", "special"],
    component: SparklesIcon,
  },
  {
    id: "bolt",
    label: "Fast Service",
    category: "offers",
    keywords: ["fast", "speed", "power", "quick"],
    component: BoltIcon,
  },
  {
    id: "rocket-launch",
    label: "Boost",
    category: "offers",
    keywords: ["boost", "launch", "growth", "fast"],
    component: RocketLaunchIcon,
  },
  {
    id: "fire",
    label: "Hot Deal",
    category: "offers",
    keywords: ["hot", "popular", "trending", "deal"],
    component: FireIcon,
  },
  {
    id: "user-group",
    label: "Team",
    category: "people",
    keywords: ["team", "staff", "people", "group", "experts"],
    component: UserGroupIcon,
  },
  {
    id: "academic-cap",
    label: "Expertise",
    category: "people",
    keywords: ["education", "expert", "training", "knowledge"],
    component: AcademicCapIcon,
  },
  {
    id: "map-pin",
    label: "Location",
    category: "locations",
    keywords: ["location", "map", "place", "visit"],
    component: MapPinIcon,
  },
  {
    id: "light-bulb",
    label: "Ideas",
    category: "ideas",
    keywords: ["idea", "insight", "smart", "tips"],
    component: LightBulbIcon,
  },
];
